// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"
	"server/ent/aaa"
)

// The ArInternalMetadatumFunc type is an adapter to allow the use of ordinary
// function as ArInternalMetadatum mutator.
type ArInternalMetadatumFunc func(context.Context, *aaa.ArInternalMetadatumMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f ArInternalMetadatumFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.ArInternalMetadatumMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.ArInternalMetadatumMutation", m)
}

// The CompanyFunc type is an adapter to allow the use of ordinary
// function as Company mutator.
type CompanyFunc func(context.Context, *aaa.CompanyMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f CompanyFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.CompanyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.CompanyMutation", m)
}

// The ExampleFunc type is an adapter to allow the use of ordinary
// function as Example mutator.
type ExampleFunc func(context.Context, *aaa.ExampleMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f ExampleFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.ExampleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.ExampleMutation", m)
}

// The SchemaMigrationFunc type is an adapter to allow the use of ordinary
// function as SchemaMigration mutator.
type SchemaMigrationFunc func(context.Context, *aaa.SchemaMigrationMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f SchemaMigrationFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.SchemaMigrationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.SchemaMigrationMutation", m)
}

// The TodoFunc type is an adapter to allow the use of ordinary
// function as Todo mutator.
type TodoFunc func(context.Context, *aaa.TodoMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f TodoFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.TodoMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.TodoMutation", m)
}

// The TodoStatusFunc type is an adapter to allow the use of ordinary
// function as TodoStatus mutator.
type TodoStatusFunc func(context.Context, *aaa.TodoStatusMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f TodoStatusFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.TodoStatusMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.TodoStatusMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *aaa.UserMutation) (aaa.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
	if mv, ok := m.(*aaa.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *aaa.UserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, aaa.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m aaa.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m aaa.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m aaa.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op aaa.Op) Condition {
	return func(_ context.Context, m aaa.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m aaa.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m aaa.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m aaa.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk aaa.Hook, cond Condition) aaa.Hook {
	return func(next aaa.Mutator) aaa.Mutator {
		return aaa.MutateFunc(func(ctx context.Context, m aaa.Mutation) (aaa.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, aaa.Delete|aaa.Create)
func On(hk aaa.Hook, op aaa.Op) aaa.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, aaa.Update|aaa.UpdateOne)
func Unless(hk aaa.Hook, op aaa.Op) aaa.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) aaa.Hook {
	return func(aaa.Mutator) aaa.Mutator {
		return aaa.MutateFunc(func(context.Context, aaa.Mutation) (aaa.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []aaa.Hook {
//		return []aaa.Hook{
//			Reject(aaa.Delete|aaa.Update),
//		}
//	}
func Reject(op aaa.Op) aaa.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []aaa.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...aaa.Hook) Chain {
	return Chain{append([]aaa.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() aaa.Hook {
	return func(mutator aaa.Mutator) aaa.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...aaa.Hook) Chain {
	newHooks := make([]aaa.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
